#include "UPTIKRigBuilder.h"

#include "UPTSettings.h"
#include "UPTSkeletonProfile.h"

#include "Engine/SkeletalMesh.h"
#include "ObjectTools.h"
#include "ReferenceSkeleton.h"
#include "Rig/IKRigDefinition.h"
#include "Rig/Solvers/IKRigFullBodyIK.h"
#include "RigEditor/IKRigController.h"
#include "RigEditor/IKRigDefinitionFactory.h"
#include "RigEditor/IKRigAutoCharacterizer.h"

namespace
{
struct FUPTChainSpec
{
    FName ChainName;
    FName StartRole;
    FName EndRole;
    bool bRequired;
};

bool ResolveBone(const UUPTSkeletonProfile* Profile, const FName Role, FName& OutBone)
{
    const FName* Bone = Profile ? Profile->BoneMappings.Find(Role) : nullptr;
    if (!Bone || Bone->IsNone()) return false;
    OutBone = *Bone;
    return true;
}
}

UIKRigDefinition* FUPTIKRigBuilder::CreateUniversalIKRig(USkeletalMesh* Mesh, FString& OutError)
{
    if (!Mesh) { OutError = TEXT("Skeletal Mesh가 없습니다."); return nullptr; }

    FString SafeName = ObjectTools::SanitizeObjectName(Mesh->GetName());
    if (SafeName.IsEmpty()) SafeName = TEXT("Skeleton");
    UIKRigDefinition* IKRig = UIKRigDefinitionFactory::CreateNewIKRigAsset(
        GetDefault<UUPTSettings>()->DefaultIKRigPath, FString(TEXT("IK_UPT_AUTO_")) + SafeName);
    if (!IKRig) { OutError = TEXT("범용 IK Rig 에셋을 생성하지 못했습니다."); return nullptr; }

    UIKRigController* Controller = UIKRigController::GetController(IKRig);
    if (!Controller || !Controller->SetSkeletalMesh(Mesh))
    { OutError = TEXT("범용 IK Rig에 Skeletal Mesh를 설정하지 못했습니다."); return nullptr; }

    // Auto Characterizer 구현체는 엔진 모듈 외부로 export되지 않으므로 공개 Controller API로 판정합니다.
    FAutoCharacterizeResults Results;
    Controller->AutoGenerateRetargetDefinition(Results);
    if (!Results.bUsedTemplate || !Controller->ApplyAutoGeneratedRetargetDefinition())
    {
        OutError = FString::Printf(
            TEXT("UE Auto Characterizer가 '%s' 구조를 알려진 휴머노이드로 판정하지 못했습니다(최고 일치도 %.0f%%)."),
            *Mesh->GetName(), Results.BestPercentageOfTemplateScore * 100.0f);
        return nullptr;
    }

    const TArray<FName> RequiredChains = {
        TEXT("Root"), TEXT("Spine"), TEXT("LeftArm"), TEXT("RightArm"), TEXT("LeftLeg"), TEXT("RightLeg")
    };
    for (const FName ChainName : RequiredChains)
    {
        if (!Controller->GetRetargetChainByName(ChainName))
        {
            OutError = FString::Printf(TEXT("자동 Characterize 결과에 필수 체인 %s가 없습니다."), *ChainName.ToString());
            return nullptr;
        }
    }

    Controller->SortRetargetChains();
    IKRig->MarkPackageDirty();
    return IKRig;
}

UIKRigDefinition* FUPTIKRigBuilder::CreateIKRig(UUPTSkeletonProfile* Profile, FString& OutError)
{
    if (!Profile) { OutError = TEXT("Skeleton Profile을 선택하세요."); return nullptr; }
    if (!Profile->bOverridesValid) { OutError = TEXT("Override 오류가 있는 Profile은 사용할 수 없습니다."); return nullptr; }
    if (Profile->RetargetReadiness < 0.70f) { OutError = TEXT("리타기팅 준비도가 70% 미만입니다. Mapping을 검수하세요."); return nullptr; }

    USkeletalMesh* Mesh = Profile->SourceMesh.LoadSynchronous();
    if (!Mesh) { OutError = TEXT("Profile의 Source Skeletal Mesh를 불러오지 못했습니다."); return nullptr; }
    const FReferenceSkeleton& Ref = Mesh->GetRefSkeleton();

    FName RetargetRoot;
    if (!ResolveBone(Profile, TEXT("Pelvis"), RetargetRoot)) { OutError = TEXT("필수 Pelvis Mapping이 없습니다."); return nullptr; }

    const TArray<FUPTChainSpec> Specs = {
        {TEXT("Root"), TEXT("Root"), TEXT("Pelvis"), true},
        {TEXT("Spine"), TEXT("Spine"), TEXT("Head"), true},
        {TEXT("LeftArm"), TEXT("LeftUpperArm"), TEXT("LeftHand"), true},
        {TEXT("RightArm"), TEXT("RightUpperArm"), TEXT("RightHand"), true},
        {TEXT("LeftLeg"), TEXT("LeftThigh"), TEXT("LeftFoot"), true},
        {TEXT("RightLeg"), TEXT("RightThigh"), TEXT("RightFoot"), true},
        {TEXT("LeftClavicle"), TEXT("LeftClavicle"), TEXT("LeftUpperArm"), false},
        {TEXT("RightClavicle"), TEXT("RightClavicle"), TEXT("RightUpperArm"), false},
        {TEXT("Neck"), TEXT("Neck"), TEXT("Head"), false}
    };

    struct FResolvedChain { FName Name; FName Start; FName End; };
    TArray<FResolvedChain> Chains;
    for (const FUPTChainSpec& Spec : Specs)
    {
        FName StartBone, EndBone;
        const bool bHasStart = ResolveBone(Profile, Spec.StartRole, StartBone);
        const bool bHasEnd = ResolveBone(Profile, Spec.EndRole, EndBone);
        if (!bHasStart || !bHasEnd)
        {
            if (Spec.bRequired) { OutError = FString::Printf(TEXT("필수 체인 %s의 Mapping이 부족합니다."), *Spec.ChainName.ToString()); return nullptr; }
            continue;
        }
        const int32 StartIndex = Ref.FindBoneIndex(StartBone);
        const int32 EndIndex = Ref.FindBoneIndex(EndBone);
        if (StartIndex == INDEX_NONE || EndIndex == INDEX_NONE)
        { OutError = FString::Printf(TEXT("체인 %s가 Source Mesh에 없는 본을 참조합니다."), *Spec.ChainName.ToString()); return nullptr; }
        if (StartIndex != EndIndex && !Ref.BoneIsChildOf(EndIndex, StartIndex))
        { OutError = FString::Printf(TEXT("체인 %s의 %s → %s 계층이 연결되지 않습니다."), *Spec.ChainName.ToString(), *StartBone.ToString(), *EndBone.ToString()); return nullptr; }
        Chains.Add({Spec.ChainName, StartBone, EndBone});
    }

    FString SafeName = ObjectTools::SanitizeObjectName(Mesh->GetName());
    if (SafeName.IsEmpty()) SafeName = TEXT("Skeleton");
    UIKRigDefinition* IKRig = UIKRigDefinitionFactory::CreateNewIKRigAsset(GetDefault<UUPTSettings>()->DefaultIKRigPath, FString(TEXT("IK_UPT_")) + SafeName);
    if (!IKRig) { OutError = TEXT("IK Rig 에셋을 생성하지 못했습니다."); return nullptr; }

    UIKRigController* Controller = UIKRigController::GetController(IKRig);
    if (!Controller || !Controller->SetSkeletalMesh(Mesh)) { OutError = TEXT("IK Rig에 Source Mesh를 설정하지 못했습니다."); return nullptr; }
    if (!Controller->SetRetargetRoot(RetargetRoot)) { OutError = TEXT("Retarget Root 설정에 실패했습니다."); return nullptr; }

    for (const FResolvedChain& Chain : Chains)
    {
        const FName CreatedName = Controller->AddRetargetChain(Chain.Name, Chain.Start, Chain.End, NAME_None);
        if (CreatedName.IsNone()) { OutError = FString::Printf(TEXT("IK Rig 체인 %s 생성에 실패했습니다."), *Chain.Name.ToString()); return nullptr; }
    }
    Controller->SortRetargetChains();
    IKRig->MarkPackageDirty();
    return IKRig;
}

#if 0 // 수동 FBIK 추가는 제거 대상 (파일 정리 승인 후 블록 삭제)
bool FUPTIKRigBuilder::AddFullBodyIK(UIKRigDefinition* IKRig, UUPTSkeletonProfile* Profile, FString& OutError)
{
    if (!IKRig || !Profile) { OutError = TEXT("IK Rig과 Skeleton Profile을 선택하세요."); return false; }
    UIKRigController* Controller = UIKRigController::GetController(IKRig);
    if (!Controller) { OutError = TEXT("IK Rig Controller를 가져오지 못했습니다."); return false; }
    if (Controller->GetNumSolvers() > 0) { OutError = TEXT("이미 Solver가 있는 IK Rig에는 자동 FBIK를 중복 추가하지 않습니다."); return false; }

    USkeletalMesh* Mesh = Profile->SourceMesh.LoadSynchronous();
    if (!Mesh || Controller->GetSkeletalMesh() != Mesh) { OutError = TEXT("IK Rig Preview Mesh와 Profile Source Mesh가 일치하지 않습니다."); return false; }

    FName Pelvis;
    if (!ResolveBone(Profile, TEXT("Pelvis"), Pelvis)) { OutError = TEXT("Pelvis Mapping이 없습니다."); return false; }

    struct FGoalSpec { FName GoalName; FName Role; FName ChainName; };
    const TArray<FGoalSpec> GoalSpecs = {
        {TEXT("LeftHand_Goal"), TEXT("LeftHand"), TEXT("LeftArm")},
        {TEXT("RightHand_Goal"), TEXT("RightHand"), TEXT("RightArm")},
        {TEXT("LeftFoot_Goal"), TEXT("LeftFoot"), TEXT("LeftLeg")},
        {TEXT("RightFoot_Goal"), TEXT("RightFoot"), TEXT("RightLeg")}
    };

    for (const FGoalSpec& Spec : GoalSpecs)
    {
        FName Bone;
        if (!ResolveBone(Profile, Spec.Role, Bone)) { OutError = FString::Printf(TEXT("FBIK 필수 Mapping %s가 없습니다."), *Spec.Role.ToString()); return false; }
        if (!Controller->GetRetargetChainByName(Spec.ChainName)) { OutError = FString::Printf(TEXT("FBIK 필수 체인 %s가 없습니다."), *Spec.ChainName.ToString()); return false; }
    }

    const int32 SolverIndex = Controller->AddSolver(FIKRigFullBodyIKSolver::StaticStruct());
    if (SolverIndex == INDEX_NONE) { OutError = TEXT("Full Body IK Solver를 추가하지 못했습니다."); return false; }
    if (!Controller->SetStartBone(Pelvis, SolverIndex)) { OutError = TEXT("Full Body IK Solver Root를 설정하지 못했습니다."); return false; }

    for (const FGoalSpec& Spec : GoalSpecs)
    {
        FName Bone;
        ResolveBone(Profile, Spec.Role, Bone);
        const FName GoalName = Controller->AddNewGoal(Spec.GoalName, Bone);
        if (GoalName.IsNone()) { OutError = FString::Printf(TEXT("Goal %s 생성에 실패했습니다."), *Spec.GoalName.ToString()); return false; }
        if (!Controller->ConnectGoalToSolver(GoalName, SolverIndex)) { OutError = FString::Printf(TEXT("Goal %s를 FBIK Solver에 연결하지 못했습니다."), *GoalName.ToString()); return false; }
        if (!Controller->SetRetargetChainGoal(Spec.ChainName, GoalName)) { OutError = FString::Printf(TEXT("Goal %s를 Retarget Chain에 연결하지 못했습니다."), *GoalName.ToString()); return false; }
    }

    FIKRigFullBodyIKSolver* Solver = static_cast<FIKRigFullBodyIKSolver*>(Controller->GetSolverAtIndex(SolverIndex));
    if (Solver)
    {
        Solver->Settings.RootBehavior = EPBIKRootBehavior::Free;
        Solver->Settings.GlobalPullChainAlpha = 0.0f;
    }

    for (const FName Bone : Profile->FingerBones) Controller->SetBoneExcluded(Bone, true);
    for (const FName Bone : Profile->FaceBones) Controller->SetBoneExcluded(Bone, true);
    for (const FUPTJointLimitPreset& Preset : Profile->JointLimitPresets)
    {
        if (!Preset.bApply) continue;
        if (Mesh->GetRefSkeleton().FindBoneIndex(Preset.Bone) == INDEX_NONE)
        { OutError = FString::Printf(TEXT("Joint Preset 본 %s가 Source Mesh에 없습니다."), *Preset.Bone.ToString()); return false; }
        const auto IsValidRange = [](const FVector2D& Range) { return Range.X >= -180.0f && Range.X <= 0.0f && Range.Y >= 0.0f && Range.Y <= 180.0f; };
        if ((Preset.bLimitX && !IsValidRange(Preset.XRange)) || (Preset.bLimitY && !IsValidRange(Preset.YRange)) || (Preset.bLimitZ && !IsValidRange(Preset.ZRange)))
        { OutError = FString::Printf(TEXT("Joint Preset %s의 Limit은 Min -180~0, Max 0~180 범위여야 합니다."), *Preset.SemanticRole.ToString()); return false; }
        Controller->AddBoneSetting(Preset.Bone, SolverIndex);
        FIKRigFBIKBoneSettings* Settings = reinterpret_cast<FIKRigFBIKBoneSettings*>(Controller->GetSettingsForBone(Preset.Bone, SolverIndex));
        if (!Settings) { OutError = FString::Printf(TEXT("Joint Preset %s 설정 생성에 실패했습니다."), *Preset.SemanticRole.ToString()); return false; }
        Settings->bUsePreferredAngles = !Preset.PreferredAngles.IsNearlyZero();
        Settings->PreferredAngles = Preset.PreferredAngles;
        if (Preset.bLimitX) { Settings->X = EPBIKLimitType::Limited; Settings->MinX = Preset.XRange.X; Settings->MaxX = Preset.XRange.Y; }
        if (Preset.bLimitY) { Settings->Y = EPBIKLimitType::Limited; Settings->MinY = Preset.YRange.X; Settings->MaxY = Preset.YRange.Y; }
        if (Preset.bLimitZ) { Settings->Z = EPBIKLimitType::Limited; Settings->MinZ = Preset.ZRange.X; Settings->MaxZ = Preset.ZRange.Y; }
    }
    IKRig->MarkPackageDirty();
    Controller->BroadcastNeedsReinitialized();
    return true;
}
#endif
